FROM node:alpine

WORKDIR '/app'

COPY ./package*.json ./

RUN npm install

#copy isn't used with docker-compose as currently using a volume
COPY . . 

CMD ["npm", "run", "start"]

# docker run -it -p 3000:3000 IMAGE_ID